<a href="https://colab.research.google.com/github/matsunagadaiki151/Pytorch_NLP_Basic/blob/master/Pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Tutorial

詳しくは[これ](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)を見てください。


## 1 : torchとは何か？

torchとは**GPUが使えて微分演算ができるnumpyみたいなもの**です。 \
pytorchでは基本的にこのtorchを使ってディープラーニングの実装をしていきます。

In [1]:
# torchをimportする。
import torch

torchは以下のように初期化します。

In [2]:
# 初期化されていない5×3の行列
x = torch.empty(5, 3)

print(x)

tensor([[2.9338e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 1.0436e-35]])


In [3]:
# 乱数で初期化された5×3の行列
x = torch.rand(5, 3)
print(x)

tensor([[0.1873, 0.4824, 0.6154],
        [0.0520, 0.0855, 0.2982],
        [0.3572, 0.7888, 0.0967],
        [0.6053, 0.4391, 0.0009],
        [0.1611, 0.7614, 0.2677]])


In [4]:
# 0で初期化された5×3の行列
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
a = [[5, 3, 4],
     [6, 4, 5]]
# 任意の値で初期化された行列
x = torch.tensor(a)
print(x)

tensor([[5, 3, 4],
        [6, 4, 5]])


torchの重要な処理

In [6]:
x = torch.rand(4, 3)
y = torch.rand(4, 3)

# 形状を確認する。(一番重要!!)
print(x.shape)
print(x.size())

print('-'*40)

# 任意のインデックスの形状を確認する。
print(x.shape[0])
print(x.shape[1])

torch.Size([4, 3])
torch.Size([4, 3])
----------------------------------------
4
3


In [7]:
# 加算
print(x + y)
print(y.add_(x))
print(torch.add(x, y))

tensor([[1.2092, 0.5111, 0.6270],
        [1.2574, 1.2392, 1.7006],
        [0.7365, 0.6379, 0.6882],
        [0.9789, 1.5794, 0.2049]])
tensor([[1.2092, 0.5111, 0.6270],
        [1.2574, 1.2392, 1.7006],
        [0.7365, 0.6379, 0.6882],
        [0.9789, 1.5794, 0.2049]])
tensor([[1.5991, 0.7064, 0.9342],
        [1.7670, 1.7095, 2.6538],
        [1.3855, 0.6854, 1.1547],
        [1.7024, 2.2403, 0.3360]])


In [8]:
# 形状を変更する。
z = x.view(2, 6)  # 4×3 → 2×6
print(z)
print(z.shape)

z = x.view(2, -1)  ## 4×3 → 2×?

print('-'*40)
print(z)
print(z.shape)

tensor([[0.3899, 0.1953, 0.3071, 0.5096, 0.4703, 0.9532],
        [0.6491, 0.0475, 0.4665, 0.7235, 0.6609, 0.1311]])
torch.Size([2, 6])
----------------------------------------
tensor([[0.3899, 0.1953, 0.3071, 0.5096, 0.4703, 0.9532],
        [0.6491, 0.0475, 0.4665, 0.7235, 0.6609, 0.1311]])
torch.Size([2, 6])


In [9]:
## 行列を結合する。
z = torch.cat([x, y])
print(z)
print(z.shape)

print('-'*40)

z = torch.cat([x, y], dim=1)
print(z)
print(z.shape)

tensor([[0.3899, 0.1953, 0.3071],
        [0.5096, 0.4703, 0.9532],
        [0.6491, 0.0475, 0.4665],
        [0.7235, 0.6609, 0.1311],
        [1.2092, 0.5111, 0.6270],
        [1.2574, 1.2392, 1.7006],
        [0.7365, 0.6379, 0.6882],
        [0.9789, 1.5794, 0.2049]])
torch.Size([8, 3])
----------------------------------------
tensor([[0.3899, 0.1953, 0.3071, 1.2092, 0.5111, 0.6270],
        [0.5096, 0.4703, 0.9532, 1.2574, 1.2392, 1.7006],
        [0.6491, 0.0475, 0.4665, 0.7365, 0.6379, 0.6882],
        [0.7235, 0.6609, 0.1311, 0.9789, 1.5794, 0.2049]])
torch.Size([4, 6])


In [10]:
## 次元数を増やす
z = x.unsqueeze(0)  # 0次元目に挿入する
print(z)
print(z.shape)

## 余計な次元数を削除する
w = z.squeeze()   
print(w)
print(w.shape)

tensor([[[0.3899, 0.1953, 0.3071],
         [0.5096, 0.4703, 0.9532],
         [0.6491, 0.0475, 0.4665],
         [0.7235, 0.6609, 0.1311]]])
torch.Size([1, 4, 3])
tensor([[0.3899, 0.1953, 0.3071],
        [0.5096, 0.4703, 0.9532],
        [0.6491, 0.0475, 0.4665],
        [0.7235, 0.6609, 0.1311]])
torch.Size([4, 3])


In [11]:
# 最大値をとるインデックスを求める
z = torch.tensor([[0.8, 0.2],
                  [0.1, 0.9],
                  [0.4, 0.6]])
print(torch.argmax(z, 1))

tensor([0, 1, 1])


## ニューラルネットワークを作ろう

torch.nnにはニューラルネットワークを作るための部品があります。

In [12]:
from torch import nn
from torch import optim
import torch.nn.functional as F

一番基本のLinear関数を定義してみます。

In [13]:
x = torch.rand(4, 2)
print(x.shape)
fc = nn.Linear(2, 1)
out = fc(x)
print(out.shape)

torch.Size([4, 2])
torch.Size([4, 1])


というわけで簡単なニューラルネットワークを作ってみましょう。 \
流れとしては、 \
1、データセットの作成 \
2、モデルの定義 \
3、学習、評価 \
という感じでやります。

今回はXORを学習するネットワークを作成します。 

In [154]:
# 学習用のデータ
dataset_x = torch.tensor([[0., 0.],
                          [0., 1.],
                          [1., 0.],
                          [1., 1.]])

# 学習用のラベル。
dataset_y = torch.tensor([0, 1, 1, 0])

次にモデルクラスを定義します。

In [156]:
class Net(nn.Module):
  # コンストラクタ
  def __init__(self):
    super(Net, self).__init__()
    self.fc1 = nn.Linear(2, 32)  # 中間層
    self.fc2 = nn.Linear(32, 32) # 中間層2
    self.fc3 = nn.Linear(32, 2)  # 出力層 : 0か1の二値分類
    
  # forwardメソッドを定義する。(forwardという名前じゃなきゃダメです。)
  def forward(self, input):
    out = F.relu(self.fc1(input))
    out = F.relu(self.fc2(out))
    out = self.fc3(out)
    return out

最後に学習用のコードを書きます。 \
学習は \
1、オプティマイザーの勾配をリセットする。\
2、データをモデルに適用する。\
3、誤差を求める \
4、誤差を逆伝搬 \
5、オプティマイザーを更新する。 \
を1セットとしてこれを何度も繰り返します。

In [157]:
model = Net()  # モデルを定義する。
criterion = nn.CrossEntropyLoss()  # 誤差関数を定義する。
optimizer = optim.SGD(model.parameters(), lr=0.1)  #オプティマイザーを定義する。

optimizer.zero_grad()  # オプティマイザーの勾配をリセットする。
output = model(dataset_x)  # データをモデルに通す
print(output)
print(output.shape)
loss = criterion(output, dataset_y)  #誤差を求める
print(loss)
loss.backward()  # 誤差を逆伝搬する。
optimizer.step()  # オプティマイザーを更新する。

tensor([[ 0.0742,  0.2253],
        [ 0.0998,  0.2220],
        [-0.1084,  0.2482],
        [-0.0700,  0.2420]], grad_fn=<AddmmBackward>)
torch.Size([4, 2])
tensor(0.6994, grad_fn=<NllLossBackward>)


関数にまとめます。

In [159]:
def train(dataset_x, dataset_y, model, criterion, optimizer):
  optimizer.zero_grad()  # 勾配を0にする。
  output = model(dataset_x)  # モデルに適用する。
  pred = torch.argmax(output, 1)
  loss = criterion(output, dataset_y)
  loss.backward()   # 逆伝搬
  optimizer.step()  # オプティマイザーを更新
  return pred, loss

最後にこれを200エポック繰り返してみます。

In [165]:
model = Net()  # モデル
criterion = nn.CrossEntropyLoss()  # 誤差関数
optimizer = optim.SGD(model.parameters(), lr=0.1)  # 最適化関数

for i in range(200):
  pred, loss = train(dataset_x, dataset_y, model, criterion, optimizer)
  if i % 10 == 0:
    print(f'epoch{i} : {loss} , {pred}')


epoch0 : 0.7092825770378113 , tensor([1, 1, 1, 1])
epoch10 : 0.6823376417160034 , tensor([1, 1, 1, 0])
epoch20 : 0.6682143211364746 , tensor([1, 0, 1, 0])
epoch30 : 0.6521492004394531 , tensor([1, 0, 1, 0])
epoch40 : 0.6309375762939453 , tensor([0, 0, 1, 0])
epoch50 : 0.6034440398216248 , tensor([0, 0, 1, 0])
epoch60 : 0.5658319592475891 , tensor([0, 1, 1, 0])
epoch70 : 0.5177656412124634 , tensor([0, 1, 1, 0])
epoch80 : 0.45663219690322876 , tensor([0, 1, 1, 0])
epoch90 : 0.3899196982383728 , tensor([0, 1, 1, 0])
epoch100 : 0.3166232705116272 , tensor([0, 1, 1, 0])
epoch110 : 0.249177485704422 , tensor([0, 1, 1, 0])
epoch120 : 0.18965952098369598 , tensor([0, 1, 1, 0])
epoch130 : 0.1424504965543747 , tensor([0, 1, 1, 0])
epoch140 : 0.10893275588750839 , tensor([0, 1, 1, 0])
epoch150 : 0.08398713916540146 , tensor([0, 1, 1, 0])
epoch160 : 0.06632223725318909 , tensor([0, 1, 1, 0])
epoch170 : 0.053558193147182465 , tensor([0, 1, 1, 0])
epoch180 : 0.04409826919436455 , tensor([0, 1, 1, 0